server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/PLAY_GROUND?characterEncoding=UTF-8&serverTimezone=UTC
    username: user
    password: userpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 80
      max-lifetime: 1800000

  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    check-template-location: true
    suffix: .html

mybatis:
  mapper-locations: classpath:mappers/**/*.xml
