server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kim
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 80
      max-lifetime: 1800000

  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    check-template-location: true
    suffix: .html

mybatis:
  mapper-locations: classpath:mappers/**/*.xml

mail:
  address: ksh251024@naver.com  # 발신자 메일
  password:                     # 메일 비번